[Crawler-Apk] Search by keyword
SkyTech-Software/skytech-scripts pull request #19
Opened 2024-03-13 21:16 UTC by morphe157

2024-03-13 21:17 UTC, morphe157 commented on backend/api_v1/commands/crawler_apk/apk_font_extractor.py
> +            "-qq",
Added it to silence annoying prompts in docker output

2024-03-13 21:18 UTC, morphe157 commented on backend/api_v1/commands/crawler_apk/apk_font_extractor.py
> +        buffer, "w", compression=zipfile.ZIP_DEFLATED, strict_timestamps=False
`strict_timestamps=False` fixes issue with fonts which has invalid last modified day.

2024-03-14 06:11 UTC, xNykram requested changes

2024-03-14 06:11 UTC, xNykram commented on pyproject.toml
> +bs4 = "0.0.2"
The latest available version of bs4 is 4.12.3, is there any reason why we used 0.0.2 here?

2024-03-14 16:01 UTC, morphe157 commented on pyproject.toml
> +bs4 = "0.0.2"
turns out `bs4` is just a dummy placeholder, outdated package for `beautifulsoup4`.

Switched to `beautifulsoup4` instead.

2024-03-14 16:18 UTC, xNykram approved these changes

2024-03-14 16:19 UTC, xNykram commented
Pls merge it to master and inform Arek.

2024-03-14 16:32 UTC, merged